# Generated by Django 4.0.5 on 2023-02-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('bookname', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('bookdate', models.CharField(max_length=200)),
                ('word', models.TextField(null=True)),
                ('introduction', models.TextField(null=True)),
                ('authorintroduction', models.TextField(null=True)),
                ('downloadlink', models.TextField(null=True)),
                ('imagelink', models.TextField(null=True)),
                ('yi', models.TextField(null=True)),
                ('label', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
                ('spare1', models.TextField(null=True)),
                ('spare2', models.TextField(null=True)),
            ],
        ),
    ]
