# Generated by Django 4.0.5 on 2023-02-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksubmit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksubmit',
            old_name='word',
            new_name='information',
        ),
    ]
